/* 😀 */ @/*@case.arkui.sdk-completion.entry.start*/Ent/*@case.arkui.sdk-completion.entry.end*//*@case.arkui.sdk-completion.entry*/
class EntryCompletionTarget {}

/* 😀 */ @/*@case.arkui.sdk-completion.component.start*/Com/*@case.arkui.sdk-completion.component.end*//*@case.arkui.sdk-completion.component*/
class ComponentCompletionTarget {}

class StateCompletionTarget {
  /* 😀 */ @/*@case.arkui.sdk-completion.state.start*/Sta/*@case.arkui.sdk-completion.state.end*//*@case.arkui.sdk-completion.state*/ value: number = 0
}

const columnFace = "😀"; const columnCandidate = /*@case.arkui.sdk-completion.column.start*/Col/*@case.arkui.sdk-completion.column.end*//*@case.arkui.sdk-completion.column*/
const textFace = "😀"; const textCandidate = /*@case.arkui.sdk-completion.text.start*/Te/*@case.arkui.sdk-completion.text.end*//*@case.arkui.sdk-completion.text*/
